name: Sync Albion recipes

on:
  workflow_dispatch: {}            # botón "Run workflow"
  schedule:
    - cron: '0 */12 * * *'         # cada 12 h (opcional; puedes cambiarlo o quitarlo)

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write              # necesario para poder commitear cambios

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fetch & build flat recipes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # token automático del runner
        run: |
          set -euxo pipefail
          node -v
          mkdir -p data
          node scripts/fetch_recipes.js
          echo "==== Files in data/ ===="
          ls -lh data || true

      - name: Commit & push (only if changed)
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: sync recipes $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes to commit"
          fi
