name: Sync Albion recipes

on:
  workflow_dispatch:      # lo podrás lanzar a mano desde Actions
  # schedule:
  #   - cron: '0 9 * * *' # (opcional) corre todos los días 09:00 UTC

permissions:
  contents: write         # necesario para poder commitear los archivos generados

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Fetch & build recipes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # token automático del runner
        run: |
          node -v
          mkdir -p data
          node scripts/fetch_recipes.js
          ls -lh data

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: sync recipes ($(date -u +%F@%H:%MZ))" || echo "No changes to commit"
          git push
