name: Sync Albion recipes
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'   # diario 06:00 UTC (puedes cambiarlo o borrar la schedule)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure folders
      - run: |
          mkdir -p formatted
          mkdir -p data

      - name: Download recipes.json from ao-data
        run: |
          curl -L \
            -H "User-Agent: AlbionCalc" \
            https://raw.githubusercontent.com/ao-data/ao-bin-dumps/master/formatted/recipes.json \
            -o formatted/recipes.json
          cp formatted/recipes.json data/recipes.json

      - name: Validate JSON size
        run: |
          node -e 'const fs=require("fs");const j=JSON.parse(fs.readFileSync("formatted/recipes.json","utf8"));if(!Array.isArray(j)||j.length<1000){console.error("Muy pocas recetas:", Array.isArray(j)?j.length:"no array");process.exit(2);}console.log("Recetas:", j.length);'

      - name: Commit if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            formatted/recipes.json
            data/recipes.json
          message: 'chore: sync recipes.json from ao-data'
